<template>
  <div class="wrapper">
    <script>
      window.muxPlayerInitTime = Date.now()
    </script>
    <h1 class="page-title">{{ talk.talk.title }}</h1>
    <p class="text-lg">
      Presented by {{ talk.speakers.map((s) => s.name).join(' & ') }}
    </p>
    <div>
      <video
        id="video"
        class="w-full mt-4 lg:mt-16 border-2 border-pink-500"
        playsinline
        controls
        preload="metadata"
      ></video>
      <p class="text-right text-sm text-gray-700 dark:text-white">
        Video hosting kindly provided by
        <a
          class="text-pink-600 dark:text-white dark:underline"
          href="https://mux.com/"
          >Mux - video for developers</a
        >
      </p>
    </div>
    <div
      class="
        flex flex-col-reverse
        lg:grid lg:grid-cols-5
        lg:flex-row
        gap-8
        lg:mt-16
      "
    >
      <main v-if="talk.body.children.length > 0" class="col-span-3">
        <h2 class="text-3xl font-bold">Transcript</h2>
        <small v-if="talk.transcript == 'machine'"
          ><p class="text-sm italic pt-4">
            These transcripts were generated by a machine and checked-over by a
            human for accuracy. Still, there may be small errors. If you spot
            any, please feel free to
            <a
              class="text-pink-600 dark:text-white dark:underline"
              :href="`https://github.com/yougotthisconf/yougotthis.io/tree/main/${talk.slug}`"
              >submit a pull request</a
            >
            with amendments.
          </p></small
        >
        <small v-else>
          <p class="text-sm italic pt-4">
            These transcripts were generated by a machine and checked-over by a
            human for accuracy. Still, there may be small errors. If you spot
            any, please feel free to
            <a
              class="text-pink-600 dark:text-white dark:underline"
              :href="`https://github.com/yougotthisconf/yougotthis.io/tree/main/${talk.slug}`"
              >submit a pull request</a
            >
            with amendments.
          </p>
        </small>
        <article>
          <nuxt-content :document="talk" class="prose mt-4 max-w-full" />
        </article>
      </main>
      <aside
        :class="{
          'col-span-2': talk.body.children.length > 0,
          'col-span-5 grid lg:grid-cols-3 gap-x-8':
            talk.body.children.length == 0,
        }"
      >
        <div class="mb-8">
          <h2 class="font-bold text-3xl">About the talk</h2>
          <p class="mt-4 mb-2 text-sm leading-relaxed">
            {{ talk.talk.abstract }}
          </p>
          <div class="py-2">
            <n-link
              v-for="tag in tags"
              :key="tag"
              class="tag"
              :to="`/talks?tag=${tag}`"
            >
              {{ tag.split('-').join(' ') }}
            </n-link>
          </div>
        </div>

        <div v-for="speaker in talk.speakers" :key="speaker.name" class="mb-12">
          <h2 class="font-bold text-3xl">About {{ speaker.name }}</h2>
          <p class="my-4 text-sm leading-relaxed">
            {{ speaker.bio }}
          </p>
          <div class="flex space-x-3 items-center">
            <img
              :src="`/img/people/${speaker.photo}`"
              :alt="`Image of ${speaker.name}`"
              class="h-10 rounded-full"
            />
            <div>
              <p>{{ speaker.name }}</p>
              <a
                v-if="speaker.twitter"
                :href="`https://twitter.com/${speaker.twitter}`"
                class="text-gray-700 text-sm block"
              >
                @{{ speaker.twitter }}
              </a>
            </div>
          </div>
        </div>

        <div class="mb-8">
          <h2 class="font-bold text-3xl">About the event</h2>
          <div class="flex space-x-3 items-center my-4">
            <img :src="eventLogo" :alt="`${talk.event} logo`" class="h-10" />
            <div>
              <p>{{ talk.event }}</p>
              <span class="text-gray-700 text-sm block">{{
                $moment(talk.date).format('Do MMM YYYY')
              }}</span>
            </div>
          </div>
          <n-link :to="`/talks?tag=${event.tag}`" class="tag">{{
            event.title.toLowerCase()
          }}</n-link>
        </div>
      </aside>
    </div>
  </div>
</template>

<script>
export default {
  async asyncData({ store, $content, params }) {
    const talk = await $content('talks', params.slug).fetch()
    const event = store.state.events.find((e) => e.title === talk.event)
    const eventLogo = `/img/events/logos/${event.logo}`
    const themeTags = store.state.tags.filter((t) => t.type === 'theme')
    const tags = talk.tags.filter((t) => themeTags.find((u) => u.name === t))
    return { talk, eventLogo, tags, event }
  },
  mounted() {
    const source = `https://stream.mux.com/${this.talk.video}.m3u8`
    const video = document.querySelector('#video')
    if (!Hls.isSupported()) { // eslint-disable-line
      video.src = source
    } else {
      const hls = new Hls() // eslint-disable-line
      hls.loadSource(source)
      hls.attachMedia(video)
      window.hls = hls
    }
    if (typeof mux !== 'undefined') {
      mux.monitor('#video', { // eslint-disable-line
        debug: false,
        data: {
          env_key: 'ebv8g7tenqkgho0bfb8ggg1s9',
          video_title: this.talk.title,
          player_init_time: window.muxPlayerInitTime,
        },
      })
    }
  },
}
</script>

<style scoped>
.tag {
  @apply inline-block rounded-full px-3 py-1 text-sm mr-2 mb-2 bg-indigo-100 lowercase text-center;
}
.tag-upper {
  @apply capitalize !important;
}
</style>
