export const state = () => ({
  past: [
    {
      title: 'You Got This In Cyberspace',
      date: '2022-01-14',
      location: 'Online',
      type: 'Conference',
      url: '/events/cyberspace',
      og: 'cyberspace.png',
      icon: 'cyberspace.png',
      sponsors: ['bryter', 'ably', 'balsamiq', 'circle-ci', 'twilio'],
      tag: 'you-got-this-in-cyberspace',
    },
    {
      title: 'You Got This Through the Seasons: Fall 2021',
      date: '2021-10-14',
      location: 'Online',
      type: 'Meetup',
      url: '/events/fall-2021',
      og: 'fall.jpg',
      icon: 'fall.png',
      sponsors: ['bryter', 'balsamiq', 'circle-ci', 'samsung-internet'],
      tag: 'you-got-this-through-the-seasons-fall-2021'
    },
    {
      title: 'You Got This Through the Seasons: Summer 2021',
      date: '2021-08-12',
      location: 'Online',
      type: 'Meetup',
      url: '/events/summer-2021',
      og: 'summer.jpg',
      icon: 'summer.png',
      sponsors: ['orbit', 'balsamiq', 'twilio', 'samsung-internet'],
      tag: 'you-got-this-through-the-seasons-summer-2021'
    },
    {
      title: 'You Got This From Your Couch',
      date: '2021-01-15',
      location: 'Online',
      type: 'Conference',
      url: 'https://couch.yougotthis.io',
      tag: 'you-got-this-from-your-couch',
      og: 'couch.png',
      icon: 'couch.png',
      sponsors: [
        '20i',
        'auth0',
        'balsamiq',
        'buzzfeed',
        'circle-ci',
        'futuregov',
        'mux',
        'samsung-internet',
        'vonage',
      ],
    },
    {
      title: 'IT Matters Conference ONLINE',
      date: '2020-09-26',
      location: 'Online',
      type: 'Conference',
      url: 'https://itmatters.pl/',
      tag: 'it-matters-online-2020',
      og: 'it-matters.png',
      icon: 'it-matters.png',
      sponsors: ['ing-tech-poland'],
    },
    {
      title: '#humansconf Open Space 2',
      date: '2020-07-15',
      location: 'Online',
      type: 'Discussion Space',
      url: 'https://www.humansconf.org/events/2020-07-15-virtual-open-space',
      og: 'humans.png',
      icon: 'humans.png',
    },
    {
      title: 'You Got This From Home',
      date: '2020-06-06',
      location: 'Online',
      type: 'Conference',
      tag: 'you-got-this-2020-from-home',
      url: 'https://home.yougotthis.io',
      og: 'home.png',
      icon: 'home.png',
      sponsors: [
        'balsamiq',
        'samsung-internet',
        'launchdarkly',
        'github',
        'vonage',
        'contentful',
      ],
    },
    {
      title: '#humansconf Open Space 1',
      date: '2020-06-02',
      location: 'Online',
      type: 'Discussion Space',
      url: 'https://www.humansconf.org/events/2020-06-02-virtual-open-space',
      og: 'humans.png',
      icon: 'humans.png',
    },
    {
      title: 'You Got This 2020',
      date: '2020-01-18',
      location: 'Birmingham, UK',
      type: 'Conference',
      tag: 'you-got-this-birmingham-2020',
      url: 'https://2020.yougotthis.io',
      og: '2020.png',
      icon: '2020.png',
      photos: '2020',
      photographer: 'Harshpal Bhirth',
      sponsors: [
        'github',
        'balsamiq',
        'mozilla',
        'twilio',
        'samsung-internet',
        'digital-ocean',
        'pusher',
        'mlh',
        'auth0',
        'proactive',
      ],
    },
    {
      title: 'Things I Wish I Knew',
      date: '2019-08-10',
      location: 'London, UK',
      type: 'Meetup',
      url: 'https://attending.io/events/things-i-wish-i-knew-1-a-meetup-for-early-career-people-in-tech',
      og: 'things-i-wish-i-knew.png',
      icon: 'things-i-wish-i-knew.png',
    },
    {
      title: 'Adulting.Dev 2019',
      date: '2019-09-07',
      location: 'New York, USA',
      type: 'Conference',
      url: 'https://2019.adulting.dev/',
      og: 'adulting.png',
      icon: 'adulting.png',
      sponsors: ['microsoft', 'mongodb', 'contentful', 'underland'],
    },
    {
      title: 'You Got This 2019',
      date: '2019-01-19',
      location: 'London, UK',
      type: 'Conference',
      tag: 'you-got-this-london-2019',
      url: 'https://2019.yougotthis.io',
      og: '2019.png',
      icon: '2019.png',
      photos: '2019',
      photographer: 'Paul Clarke',
      sponsors: [
        'hired',
        'verve',
        'mongodb',
        'twilio',
        'github',
        'and-digital',
        'wildrocket',
        'indee',
        'futuregov',
        'monzo',
        'not-binary',
        'proactive',
        'samsung-internet',
        'dxw',
        'buzzfeed',
        'nedap',
        'mlh',
        'balsamiq',
      ],
    },
  ],
})
