export const state = () => ({
  events: [
    {
      title: 'You Got This From Your Couch',
      date: '2021-01-15',
      location: 'Online',
      type: 'Conference',
      url: 'https://couch.yougotthis.io',
      tag: 'you-got-this-from-your-couch',
      logo: 'couch.png',
    },
    {
      title: 'IT Matters Conference ONLINE',
      date: '2020-09-26',
      location: 'Online',
      type: 'Conference',
      url: 'https://itmatters.pl/',
      tag: 'it-matters-online-2020',
      logo: 'it-matters.png',
    },
    {
      title: '#humansconf Open Space 2',
      date: '2020-07-15',
      location: 'Online',
      type: 'Discussion Space',
      url: 'https://www.humansconf.org/events/2020-07-15-virtual-open-space',
      logo: 'humans.png',
    },
    {
      title: 'You Got This From Home',
      date: '2020-06-06',
      location: 'Online',
      type: 'Conference',
      tag: 'you-got-this-2020-from-home',
      url: 'https://home.yougotthis.io',
      logo: 'home.png',
    },
    {
      title: '#humansconf Open Space 1',
      date: '2020-06-02',
      location: 'Online',
      type: 'Discussion Space',
      url: 'https://www.humansconf.org/events/2020-06-02-virtual-open-space',
      logo: 'humans.png',
    },
    {
      title: 'You Got This 2020',
      date: '2020-01-18',
      location: 'Birmingham, UK',
      type: 'Conference',
      tag: 'you-got-this-birmingham-2020',
      url: 'https://2020.yougotthis.io',
      logo: '2020.png',
    },
    {
      title: 'Things I Wish I Knew',
      date: '2019-08-10',
      location: 'London, UK',
      type: 'Meetup',
      url: 'https://attending.io/events/things-i-wish-i-knew-1-a-meetup-for-early-career-people-in-tech',
      logo: 'things-i-wish-i-knew.png',
    },
    {
      title: 'Adulting.Dev 2019',
      date: '2019-09-07',
      location: 'New York, USA',
      type: 'Conference',
      url: 'https://2019.adulting.dev/',
      logo: 'adulting.png',
    },
    {
      title: 'You Got This 2019',
      date: '2019-01-19',
      location: 'London, UK',
      type: 'Conference',
      tag: 'you-got-this-london-2019',
      url: 'https://2019.yougotthis.io',
      logo: '2019.png',
    },
  ],
  tags: [
    { name: 'diversity-accessibility-inclusion', type: 'theme' },
    { name: 'ethics-in-tech', type: 'theme' },
    { name: 'managers', type: 'theme' },
    { name: 'professional-development', type: 'theme' },
    { name: 'self-advocacy', type: 'theme' },
    { name: 'self-care', type: 'theme' },
    { name: 'working-with-others', type: 'theme' },
    { name: 'you-got-this-2020-from-home', type: 'event' },
    { name: 'you-got-this-birmingham-2020', type: 'event' },
    { name: 'you-got-this-from-your-couch', type: 'event' },
    { name: 'you-got-this-london-2019', type: 'event' },
    { name: 'it-matters-online-2020', type: 'event' },
  ],
  sponsors: [
    '20i',
    'and-digital',
    'auth0',
    'balsamiq',
    'buzzfeed',
    'circle-ci',
    'contentful',
    'digital-ocean',
    'dxw',
    'futuregov',
    'github',
    'hired',
    'indee',
    'launchdarkly',
    'mlab',
    'mlh',
    'mongodb',
    'monzo',
    'mozilla',
    'mux',
    'nedap',
    'not-binary',
    'proactive',
    'pusher',
    'samsung-internet',
    'twilio',
    'underland',
    'verve',
    'vonage',
    'wildrocket',
  ],
})
